package ar.edu.utn.sigmaproject.service;

import java.util.List;

import ar.edu.utn.sigmaproject.domain.RequirementPlanDetailRawMaterial;

public interface RequirementPlanDetailRawMaterialService {
	
	List<RequirementPlanDetailRawMaterial> getRequirementPlanDetailRawMaterialList();
	
	List<RequirementPlanDetailRawMaterial> getRequirementPlanDetailRawMaterialList(Integer idRequirementPlan);
	
	RequirementPlanDetailRawMaterial getRequirementPlanDetailRawMaterial(Integer idRequirementPlan, Integer idRawMaterialType);

	RequirementPlanDetailRawMaterial saveRequirementPlanDetailRawMaterial(RequirementPlanDetailRawMaterial requirementPlanDetailRawMaterial);

	RequirementPlanDetailRawMaterial updateRequirementPlanDetailRawMaterial(RequirementPlanDetailRawMaterial requirementPlanDetailRawMaterial);

	void deleteRequirementPlanDetailRawMaterial(RequirementPlanDetailRawMaterial requirementPlanDetailRawMaterial);

	void deleteAll(Integer idRequirementPlan);

}
